name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: zawye21/api
  IMAGE_TAG: ${{ github.sha }}

jobs:

# -----------------------------------
# 1️⃣ Static Code Analysis
# -----------------------------------
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true


    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Linter
        run: pip install flake8

      - name: Run Linter
        run: flake8 app/

# -----------------------------------
# 2️⃣ Unit Tests
# -----------------------------------
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest

# -----------------------------------
# 3️⃣ Build & Push Docker Image
# -----------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    continue-on-error: true

    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

# -----------------------------------
# 4️⃣ Deploy to Kubernetes
# -----------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/api \
            api=$IMAGE_NAME:$IMAGE_TAG \
            -n prod

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/api -n prod
